### ISSUE TITLE
Can't run with ModCheck

### ISSUE THREAD

**Issue by 6yXJI0** [Nightinggale/ModCheck#2]
ReflectionTypeLoadException getting types in assembly ModCheck: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at Verse.ModAssemblyHandler.AssemblyIsUsable (System.Reflection.Assembly asm) [0x00000] in <filename unknown>:0 

Loader exceptions:
   => System.TypeLoadException: Could not load type 'Harmony.CodeInstruction' from assembly '0Harmony, Version=1.0.9.1, Culture=neutral, PublicKeyToken=null'.

Verse.Log:Error(String)
Verse.ModAssemblyHandler:AssemblyIsUsable(Assembly)
Verse.ModAssemblyHandler:ReloadAll()
Verse.ModContentPack:ReloadContent()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.Root:<Start>m__1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()

[ModsConfig.zip](https://github.com/Nightinggale/ModCheck/files/2072043/ModsConfig.zip)

**Comment by Nightinggale** [comment]
The cause of this is 0Harmony.dll was missing in the steam version (not the GitHub release or git repository). It's added and should work now.
