### ISSUE TITLE
Profiling patches

### ISSUE THREAD

**Issue by Alexis-Grimm** [Nightinggale/ModCheck#4]
Just wondering how to profile my patches, as the link in the wiki sends me back to the home section, i don't doubt that this will drastically improve my patch speed, i just want to check out the exact numbers.

**Comment by Nightinggale** [comment]
Open Options, enable development mode and verbose logging. Restart the game and ModCheck will write the profiling results to the log. Do note that it's just normal log messages, not warnings or errors, meaning it will not trigger the log to open automatically. Also it's one of the last log entries when you reach the main menu while ModCheck patch operation output is usually at the top.
